name-template: "Release v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - feature
  - title: "🐛 Fixes"
    labels:
      - bug
  - title: "🧰 Maintenance"
    labels:
      - chore
change-template: "- ${{PR_TITLE}} (#${{PR_NUMBER}} by @${{AUTHOR_LOGIN}})"
no-changes-template: "No changes in this release."

template: |
  ## Changes
  $CHANGES
