# .github/release-drafter-config.yml
# This file configures how your release notes are built.

name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

# Template for the release notes body
template: |
  ## What's Changed
  $CHANGES
