# .github/workflows/release-drafter.yml
name: Draft Release Notes

on:
  push:
    branches:
      - stage # Runs when PRs are merged into stage

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          # Use a config file to customize labels and categories
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
